// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cardsmessage.proto

package com.sdkcdg.proto;

public final class CardsProto {
  private CardsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CardsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protofiles.CardsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string FirstCard = 5;</code>
     */
    boolean hasFirstCard();
    /**
     * <code>required string FirstCard = 5;</code>
     */
    java.lang.String getFirstCard();
    /**
     * <code>required string FirstCard = 5;</code>
     */
    com.google.protobuf.ByteString
        getFirstCardBytes();

    /**
     * <code>optional string SecondCard = 4;</code>
     */
    boolean hasSecondCard();
    /**
     * <code>optional string SecondCard = 4;</code>
     */
    java.lang.String getSecondCard();
    /**
     * <code>optional string SecondCard = 4;</code>
     */
    com.google.protobuf.ByteString
        getSecondCardBytes();
  }
  /**
   * Protobuf type {@code protofiles.CardsMessage}
   */
  public static final class CardsMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protofiles.CardsMessage)
      CardsMessageOrBuilder {
    // Use CardsMessage.newBuilder() to construct.
    private CardsMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CardsMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CardsMessage defaultInstance;
    public static CardsMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CardsMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CardsMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              secondCard_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              firstCard_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdkcdg.proto.CardsProto.internal_static_protofiles_CardsMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdkcdg.proto.CardsProto.internal_static_protofiles_CardsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdkcdg.proto.CardsProto.CardsMessage.class, com.sdkcdg.proto.CardsProto.CardsMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<CardsMessage> PARSER =
        new com.google.protobuf.AbstractParser<CardsMessage>() {
      public CardsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CardsMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CardsMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FIRSTCARD_FIELD_NUMBER = 5;
    private java.lang.Object firstCard_;
    /**
     * <code>required string FirstCard = 5;</code>
     */
    public boolean hasFirstCard() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string FirstCard = 5;</code>
     */
    public java.lang.String getFirstCard() {
      java.lang.Object ref = firstCard_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstCard_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FirstCard = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFirstCardBytes() {
      java.lang.Object ref = firstCard_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstCard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECONDCARD_FIELD_NUMBER = 4;
    private java.lang.Object secondCard_;
    /**
     * <code>optional string SecondCard = 4;</code>
     */
    public boolean hasSecondCard() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string SecondCard = 4;</code>
     */
    public java.lang.String getSecondCard() {
      java.lang.Object ref = secondCard_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          secondCard_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string SecondCard = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSecondCardBytes() {
      java.lang.Object ref = secondCard_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secondCard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      firstCard_ = "";
      secondCard_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFirstCard()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(4, getSecondCardBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(5, getFirstCardBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSecondCardBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getFirstCardBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdkcdg.proto.CardsProto.CardsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sdkcdg.proto.CardsProto.CardsMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protofiles.CardsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protofiles.CardsMessage)
        com.sdkcdg.proto.CardsProto.CardsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdkcdg.proto.CardsProto.internal_static_protofiles_CardsMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdkcdg.proto.CardsProto.internal_static_protofiles_CardsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdkcdg.proto.CardsProto.CardsMessage.class, com.sdkcdg.proto.CardsProto.CardsMessage.Builder.class);
      }

      // Construct using com.sdkcdg.proto.CardsProto.CardsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        firstCard_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        secondCard_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sdkcdg.proto.CardsProto.internal_static_protofiles_CardsMessage_descriptor;
      }

      public com.sdkcdg.proto.CardsProto.CardsMessage getDefaultInstanceForType() {
        return com.sdkcdg.proto.CardsProto.CardsMessage.getDefaultInstance();
      }

      public com.sdkcdg.proto.CardsProto.CardsMessage build() {
        com.sdkcdg.proto.CardsProto.CardsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sdkcdg.proto.CardsProto.CardsMessage buildPartial() {
        com.sdkcdg.proto.CardsProto.CardsMessage result = new com.sdkcdg.proto.CardsProto.CardsMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstCard_ = firstCard_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.secondCard_ = secondCard_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sdkcdg.proto.CardsProto.CardsMessage) {
          return mergeFrom((com.sdkcdg.proto.CardsProto.CardsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sdkcdg.proto.CardsProto.CardsMessage other) {
        if (other == com.sdkcdg.proto.CardsProto.CardsMessage.getDefaultInstance()) return this;
        if (other.hasFirstCard()) {
          bitField0_ |= 0x00000001;
          firstCard_ = other.firstCard_;
          onChanged();
        }
        if (other.hasSecondCard()) {
          bitField0_ |= 0x00000002;
          secondCard_ = other.secondCard_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFirstCard()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sdkcdg.proto.CardsProto.CardsMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sdkcdg.proto.CardsProto.CardsMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstCard_ = "";
      /**
       * <code>required string FirstCard = 5;</code>
       */
      public boolean hasFirstCard() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string FirstCard = 5;</code>
       */
      public java.lang.String getFirstCard() {
        java.lang.Object ref = firstCard_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstCard_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FirstCard = 5;</code>
       */
      public com.google.protobuf.ByteString
          getFirstCardBytes() {
        java.lang.Object ref = firstCard_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstCard_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FirstCard = 5;</code>
       */
      public Builder setFirstCard(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string FirstCard = 5;</code>
       */
      public Builder clearFirstCard() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstCard_ = getDefaultInstance().getFirstCard();
        onChanged();
        return this;
      }
      /**
       * <code>required string FirstCard = 5;</code>
       */
      public Builder setFirstCardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstCard_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object secondCard_ = "";
      /**
       * <code>optional string SecondCard = 4;</code>
       */
      public boolean hasSecondCard() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string SecondCard = 4;</code>
       */
      public java.lang.String getSecondCard() {
        java.lang.Object ref = secondCard_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            secondCard_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string SecondCard = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSecondCardBytes() {
        java.lang.Object ref = secondCard_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secondCard_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string SecondCard = 4;</code>
       */
      public Builder setSecondCard(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        secondCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string SecondCard = 4;</code>
       */
      public Builder clearSecondCard() {
        bitField0_ = (bitField0_ & ~0x00000002);
        secondCard_ = getDefaultInstance().getSecondCard();
        onChanged();
        return this;
      }
      /**
       * <code>optional string SecondCard = 4;</code>
       */
      public Builder setSecondCardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        secondCard_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protofiles.CardsMessage)
    }

    static {
      defaultInstance = new CardsMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protofiles.CardsMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protofiles_CardsMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protofiles_CardsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022cardsmessage.proto\022\nprotofiles\"5\n\014Card" +
      "sMessage\022\021\n\tFirstCard\030\005 \002(\t\022\022\n\nSecondCar" +
      "d\030\004 \001(\tB\036\n\020com.sdkcdg.protoB\nCardsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protofiles_CardsMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protofiles_CardsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protofiles_CardsMessage_descriptor,
        new java.lang.String[] { "FirstCard", "SecondCard", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
