// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playermessage.proto

package com.sdkcdg.proto;

public final class PlayerProto {
  private PlayerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protofiles.PlayerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 mAction = 5;</code>
     */
    boolean hasMAction();
    /**
     * <code>required int32 mAction = 5;</code>
     */
    int getMAction();

    /**
     * <code>required string mName = 2;</code>
     */
    boolean hasMName();
    /**
     * <code>required string mName = 2;</code>
     */
    java.lang.String getMName();
    /**
     * <code>required string mName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMNameBytes();

    /**
     * <code>optional bytes messageByteString = 3;</code>
     */
    boolean hasMessageByteString();
    /**
     * <code>optional bytes messageByteString = 3;</code>
     */
    com.google.protobuf.ByteString getMessageByteString();
  }
  /**
   * Protobuf type {@code protofiles.PlayerMessage}
   */
  public static final class PlayerMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protofiles.PlayerMessage)
      PlayerMessageOrBuilder {
    // Use PlayerMessage.newBuilder() to construct.
    private PlayerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerMessage defaultInstance;
    public static PlayerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              mName_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              messageByteString_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000001;
              mAction_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdkcdg.proto.PlayerProto.internal_static_protofiles_PlayerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdkcdg.proto.PlayerProto.internal_static_protofiles_PlayerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdkcdg.proto.PlayerProto.PlayerMessage.class, com.sdkcdg.proto.PlayerProto.PlayerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerMessage> PARSER =
        new com.google.protobuf.AbstractParser<PlayerMessage>() {
      public PlayerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MACTION_FIELD_NUMBER = 5;
    private int mAction_;
    /**
     * <code>required int32 mAction = 5;</code>
     */
    public boolean hasMAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 mAction = 5;</code>
     */
    public int getMAction() {
      return mAction_;
    }

    public static final int MNAME_FIELD_NUMBER = 2;
    private java.lang.Object mName_;
    /**
     * <code>required string mName = 2;</code>
     */
    public boolean hasMName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string mName = 2;</code>
     */
    public java.lang.String getMName() {
      java.lang.Object ref = mName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string mName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMNameBytes() {
      java.lang.Object ref = mName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEBYTESTRING_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString messageByteString_;
    /**
     * <code>optional bytes messageByteString = 3;</code>
     */
    public boolean hasMessageByteString() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes messageByteString = 3;</code>
     */
    public com.google.protobuf.ByteString getMessageByteString() {
      return messageByteString_;
    }

    private void initFields() {
      mAction_ = 0;
      mName_ = "";
      messageByteString_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, messageByteString_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(5, mAction_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, messageByteString_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, mAction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.sdkcdg.proto.PlayerProto.PlayerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sdkcdg.proto.PlayerProto.PlayerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protofiles.PlayerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protofiles.PlayerMessage)
        com.sdkcdg.proto.PlayerProto.PlayerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdkcdg.proto.PlayerProto.internal_static_protofiles_PlayerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdkcdg.proto.PlayerProto.internal_static_protofiles_PlayerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdkcdg.proto.PlayerProto.PlayerMessage.class, com.sdkcdg.proto.PlayerProto.PlayerMessage.Builder.class);
      }

      // Construct using com.sdkcdg.proto.PlayerProto.PlayerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mAction_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        mName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        messageByteString_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sdkcdg.proto.PlayerProto.internal_static_protofiles_PlayerMessage_descriptor;
      }

      public com.sdkcdg.proto.PlayerProto.PlayerMessage getDefaultInstanceForType() {
        return com.sdkcdg.proto.PlayerProto.PlayerMessage.getDefaultInstance();
      }

      public com.sdkcdg.proto.PlayerProto.PlayerMessage build() {
        com.sdkcdg.proto.PlayerProto.PlayerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sdkcdg.proto.PlayerProto.PlayerMessage buildPartial() {
        com.sdkcdg.proto.PlayerProto.PlayerMessage result = new com.sdkcdg.proto.PlayerProto.PlayerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mAction_ = mAction_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mName_ = mName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messageByteString_ = messageByteString_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sdkcdg.proto.PlayerProto.PlayerMessage) {
          return mergeFrom((com.sdkcdg.proto.PlayerProto.PlayerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sdkcdg.proto.PlayerProto.PlayerMessage other) {
        if (other == com.sdkcdg.proto.PlayerProto.PlayerMessage.getDefaultInstance()) return this;
        if (other.hasMAction()) {
          setMAction(other.getMAction());
        }
        if (other.hasMName()) {
          bitField0_ |= 0x00000002;
          mName_ = other.mName_;
          onChanged();
        }
        if (other.hasMessageByteString()) {
          setMessageByteString(other.getMessageByteString());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMAction()) {
          
          return false;
        }
        if (!hasMName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sdkcdg.proto.PlayerProto.PlayerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sdkcdg.proto.PlayerProto.PlayerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mAction_ ;
      /**
       * <code>required int32 mAction = 5;</code>
       */
      public boolean hasMAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 mAction = 5;</code>
       */
      public int getMAction() {
        return mAction_;
      }
      /**
       * <code>required int32 mAction = 5;</code>
       */
      public Builder setMAction(int value) {
        bitField0_ |= 0x00000001;
        mAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 mAction = 5;</code>
       */
      public Builder clearMAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mAction_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mName_ = "";
      /**
       * <code>required string mName = 2;</code>
       */
      public boolean hasMName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string mName = 2;</code>
       */
      public java.lang.String getMName() {
        java.lang.Object ref = mName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string mName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMNameBytes() {
        java.lang.Object ref = mName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string mName = 2;</code>
       */
      public Builder setMName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string mName = 2;</code>
       */
      public Builder clearMName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mName_ = getDefaultInstance().getMName();
        onChanged();
        return this;
      }
      /**
       * <code>required string mName = 2;</code>
       */
      public Builder setMNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString messageByteString_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes messageByteString = 3;</code>
       */
      public boolean hasMessageByteString() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes messageByteString = 3;</code>
       */
      public com.google.protobuf.ByteString getMessageByteString() {
        return messageByteString_;
      }
      /**
       * <code>optional bytes messageByteString = 3;</code>
       */
      public Builder setMessageByteString(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        messageByteString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes messageByteString = 3;</code>
       */
      public Builder clearMessageByteString() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messageByteString_ = getDefaultInstance().getMessageByteString();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protofiles.PlayerMessage)
    }

    static {
      defaultInstance = new PlayerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protofiles.PlayerMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protofiles_PlayerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protofiles_PlayerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023playermessage.proto\022\nprotofiles\"J\n\rPla" +
      "yerMessage\022\017\n\007mAction\030\005 \002(\005\022\r\n\005mName\030\002 \002" +
      "(\t\022\031\n\021messageByteString\030\003 \001(\014B\037\n\020com.sdk" +
      "cdg.protoB\013PlayerProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protofiles_PlayerMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protofiles_PlayerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protofiles_PlayerMessage_descriptor,
        new java.lang.String[] { "MAction", "MName", "MessageByteString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
